### PR TITLE
Add nodeschool workshop link

### PR DESCRIPTION
**Pull request by ryanramage**
A great resource for people to learn lots of cool things.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Are there any dates to share? Will anyone from this be at the meetup tonight who I can point out?

**Comment by ryanramage** [comment]
This link is more for the tutorials offered.

"Workshopper is the name used for the open source lesson modules associated with NodeSchool. All are self guided (you don't need to attend a workshop to do one) and most work offline."

**Comment by MarkBennett** [comment]
Cool! I've never seen this before!

**Comment by ryanramage** [comment]
I actually would like to run a nodeschool here in town, so tonight I will ask who might be interested in both attending, and mentoring one. I guess we could just run one at a future exchangejs timeslot

**Pull request merged**
